import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    SUPABASE_URL: z.ZodString;
    SUPABASE_SERVICE_KEY: z.ZodString;
    SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SUPABASE_URL: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    LIVEKIT_API_KEY: z.ZodOptional<z.ZodString>;
    LIVEKIT_API_SECRET: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_LIVEKIT_URL: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_API_URL: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_SOCKET_URL: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["fatal", "error", "warn", "info", "debug", "trace"]>>;
    EXTENSION_WS_URL: z.ZodDefault<z.ZodString>;
    AI_API_KEY: z.ZodOptional<z.ZodString>;
    AI_GROQ_API_KEY: z.ZodOptional<z.ZodString>;
    AI_GEMINI_API_KEY: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    CLOUDFLARE_API_TOKEN: z.ZodOptional<z.ZodString>;
    STRIPE_SECRET_KEY: z.ZodOptional<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.ZodOptional<z.ZodString>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    POSTHOG_API_KEY: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    REDIS_URL: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    CORS_ORIGIN: string;
    SUPABASE_URL: string;
    SUPABASE_SERVICE_KEY: string;
    NEXT_PUBLIC_API_URL: string;
    NEXT_PUBLIC_SOCKET_URL: string;
    LOG_LEVEL: "fatal" | "error" | "warn" | "info" | "debug" | "trace";
    EXTENSION_WS_URL: string;
    SUPABASE_ANON_KEY?: string | undefined;
    NEXT_PUBLIC_SUPABASE_URL?: string | undefined;
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    LIVEKIT_API_KEY?: string | undefined;
    LIVEKIT_API_SECRET?: string | undefined;
    NEXT_PUBLIC_LIVEKIT_URL?: string | undefined;
    AI_API_KEY?: string | undefined;
    AI_GROQ_API_KEY?: string | undefined;
    AI_GEMINI_API_KEY?: string | undefined;
    CLOUDFLARE_ACCOUNT_ID?: string | undefined;
    CLOUDFLARE_API_TOKEN?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: string | undefined;
    SENTRY_DSN?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
}, {
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    SUPABASE_URL: string;
    SUPABASE_SERVICE_KEY: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    PORT?: number | undefined;
    REDIS_URL?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    NEXT_PUBLIC_SUPABASE_URL?: string | undefined;
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string | undefined;
    LIVEKIT_API_KEY?: string | undefined;
    LIVEKIT_API_SECRET?: string | undefined;
    NEXT_PUBLIC_LIVEKIT_URL?: string | undefined;
    NEXT_PUBLIC_API_URL?: string | undefined;
    NEXT_PUBLIC_SOCKET_URL?: string | undefined;
    LOG_LEVEL?: "fatal" | "error" | "warn" | "info" | "debug" | "trace" | undefined;
    EXTENSION_WS_URL?: string | undefined;
    AI_API_KEY?: string | undefined;
    AI_GROQ_API_KEY?: string | undefined;
    AI_GEMINI_API_KEY?: string | undefined;
    CLOUDFLARE_ACCOUNT_ID?: string | undefined;
    CLOUDFLARE_API_TOKEN?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: string | undefined;
    SENTRY_DSN?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function getEnv(): Env;
export declare function isProduction(): boolean;
export declare function isDevelopment(): boolean;
export {};
//# sourceMappingURL=env.d.ts.map