-- SyncSaga Rollback 008: Drop All RLS Policies
-- Idempotent: YES

DROP POLICY IF EXISTS "Achievements viewable by anyone" ON public.achievements;
DROP POLICY IF EXISTS "Users can view own achievements" ON public.user_achievements;
DROP POLICY IF EXISTS "Users can schedule rooms" ON public.scheduled_rooms;
DROP POLICY IF EXISTS "Scheduled rooms viewable" ON public.scheduled_rooms;
DROP POLICY IF EXISTS "Users can manage own watch events" ON public.watch_events;
DROP POLICY IF EXISTS "Users can manage own clips" ON public.clips;
DROP POLICY IF EXISTS "Users can create clips" ON public.clips;
DROP POLICY IF EXISTS "Public clips viewable" ON public.clips;
DROP POLICY IF EXISTS "Users can react in joined rooms" ON public.timeline_reactions;
DROP POLICY IF EXISTS "Timeline reactions viewable by room members" ON public.timeline_reactions;
DROP POLICY IF EXISTS "Users can create activity entries" ON public.activity_feed;
DROP POLICY IF EXISTS "Activity feed viewable by friends" ON public.activity_feed;
DROP POLICY IF EXISTS "Conversations viewable by participants" ON public.conversations;
DROP POLICY IF EXISTS "System can insert notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can view own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Message reactions viewable by participants" ON public.message_reactions;
DROP POLICY IF EXISTS "Users can manage own message reactions" ON public.message_reactions;
DROP POLICY IF EXISTS "Users can send messages" ON public.messages;
DROP POLICY IF EXISTS "Messages viewable in joined rooms or DMs" ON public.messages;
DROP POLICY IF EXISTS "Users can update own friendships" ON public.friendships;
DROP POLICY IF EXISTS "Users can send friend requests" ON public.friendships;
DROP POLICY IF EXISTS "Friendships viewable by participants" ON public.friendships;
DROP POLICY IF EXISTS "Users can manage own embed configs" ON public.embed_configs;
DROP POLICY IF EXISTS "Members can create invites" ON public.room_invites;
DROP POLICY IF EXISTS "Invites viewable by participants" ON public.room_invites;
DROP POLICY IF EXISTS "Users can leave rooms" ON public.room_members;
DROP POLICY IF EXISTS "Users can join rooms" ON public.room_members;
DROP POLICY IF EXISTS "Members viewable by room members" ON public.room_members;
DROP POLICY IF EXISTS "Host can update own room" ON public.rooms;
DROP POLICY IF EXISTS "Users can create rooms" ON public.rooms;
DROP POLICY IF EXISTS "Private rooms viewable by members" ON public.rooms;
DROP POLICY IF EXISTS "Public rooms are viewable" ON public.rooms;
DROP POLICY IF EXISTS "Users can see own reports" ON public.reports;
DROP POLICY IF EXISTS "Users can create reports" ON public.reports;
DROP POLICY IF EXISTS "Users can manage own API keys" ON public.api_keys;
DROP POLICY IF EXISTS "Users can manage own webhooks" ON public.webhooks;
DROP POLICY IF EXISTS "Bans manageable by admins" ON public.bans;
DROP POLICY IF EXISTS "Users can see if they are blocked" ON public.blocked_users;
DROP POLICY IF EXISTS "Users can manage own blocks" ON public.blocked_users;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON public.profiles;

ALTER TABLE public.user_achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.watch_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.clips DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_feed DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.embed_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bans DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
